---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-istio-csr
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  releaseName: cert-manager-isito-csr
  chart:
    spec:
      chart: cert-manager-istio-csr
      # version: "1.13.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 10m0s
  values:
    app:
      certmanager:
        issuer:
          name: istio-ca
          kind: Issuer
          group: cert-manager.io