apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: monitoring
spec:
  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces:
    - '**'
    ingress:
      enabled: false
    namespace: monitoring
    logger:
      log_level: info
  server:
    profiler:
      enabled: false
  external_services:
    istio:
      root_namespace: istio-system
      # config_map_name: istio
      # istio_sidecar_injector_config_map_name: istio-sidecar-injector
      # istiod_deployment_name: istiod
      component_status:
        enabled: true
        components:
        - app_label: istio-ingressgateway
          is_core: true
          is_proxy: true
          namespace: istio-system
        - app_label: ingressgateway-external
          is_core: true
          is_proxy: true
          namespace: istio-system
    grafana:
      in_cluster_url: http://prometheus-operator-grafana.monitoring.svc:80
      url: http://prometheus-operator-grafana.monitoring.svc:80
    prometheus:
      in_cluster_url: http://prometheus-operated.monitoring.svc:9090
      url: http://prometheus-operated.monitoring.svc:9090
    tracing:
      in_cluster_url: http://tracing-query.monitoring.svc:16686
      url: http://tracing-query.monitoring.svc:16686