apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    ingress:
      enabled: false
    namespace: kiali-operator
    logger:
      log_level: info
  server:
    profiler:
      enabled: false