apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: monitoring
spec:
  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    ingress:
      enabled: false
    namespace: monitoring
    logger:
      log_level: info
  server:
    profiler:
      enabled: false
  external_services:
    grafana:
      in_cluster_url: http://prometheus-operator-grafana.monitoring.svc:80
      url: http://prometheus-operator-grafana.monitoring.svc:80
    prometheus:
      url: http://prometheus-operated.monitoring.svc:9090
    # tracing:
    #   url: http://jaeger-query:16686