apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: monitoring
spec:
  istio_namespace: aks-istio-system
  auth:
    strategy: anonymous
  deployment:
    ingress:
      enabled: false
    namespace: monitoring
    logger:
      log_level: info
  server:
    profiler:
      enabled: false
  external_services:
    istio:
      root_namespace: aks-istio-system
      config_map_name: istio-asm-1-19
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-asm-1-19
      istiod_deployment_name: istiod-asm-1-19
      component_status:
        enabled: true
        components:
        # - app_label: istiod
        #   is_core: true
        - app_label: istio-ingressgateway
          is_core: true
          is_proxy: true
          namespace: aks-istio-ingress
    grafana:
      in_cluster_url: http://prometheus-operator-grafana.monitoring.svc:80
      url: http://prometheus-operator-grafana.monitoring.svc:80
    prometheus:
      url: http://prometheus-operated.monitoring.svc:9090
    # tracing:
    #   url: http://jaeger-query:16686