apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: monitoring
spec:
  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    ingress:
      enabled: false
    namespace: monitoring
    logger:
      log_level: info
  server:
    profiler:
      enabled: false
  external_services:
    grafana:
      url: http://prometheus-operator-grafana.monitoring.svc.cluster.local:80
    prometheus_config:
      url: http://prometheus-operated.monitor.monitoring.cluster.local:9090
    # tracing:
    #   url: http://jaeger-query:16686