---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-service
  namespace: osdu-azure
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  releaseName: default-service
  dependsOn:
  - name: osdu-developer-base
    namespace: default
  chart:
    spec:
      chart: ./charts/osdu-developer-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
