---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  chart:
    spec:
      chart: ./charts/env-debug
      sourceRef:
        kind: GitRepository
        name: osdu-developer
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: dev-sample
  values:
    replicaCount: 1
    nameOverride: ""
    fullnameOverride: env-debug
    service:
      type: ClusterIP
      port: 80
    env:
    - name: MESSAGE
      value: Hello World!
  