---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev-sample
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  chart:
    spec:
      chart: ./charts/env-debug
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: dev-sample
  values:
    replicaCount: 1
    nameOverride: ""
    fullnameOverride: env-debug
    service:
      type: ClusterIP
      port: 80
    env:
    - name: MESSAGE
      value: Hello World!
  