{{- $namespace := .Release.Namespace }}
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: {{ include "config-maps.fullname" . }}-services
  namespace: {{ $namespace }}
spec:
  endpoint: {{ .Values.azure.configEndpoint }}
  target:
    configMapName: configmap-services
    # configMapData:
    #   type: yaml
    #   key: value.yaml
    #   separator: "."
  auth:
    workloadIdentity:
      managedIdentityClientId: {{ .Values.azure.clientId }}
  configuration:
     selectors:
        - keyFilter: "*"
          labelFilter: "configmap-services"