---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: istio-base
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    defaultRevision: default
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-istio-csr
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-istio-csr
      # version: "1.13.x"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 1h0m0s
  values:
    app:
      certmanager:
        issuer:
          name: istio-ca
          kind: Issuer
          group: cert-manager.io
