apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal-gateway
  namespace: istio-system
spec:
  selector:
    istio: istio-ingressgateway-internal
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP     
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: external-gateway
  namespace: istio-system
spec:
  selector:
    istio: istio-ingressgateway-external
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP