---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    egressGateways:
      - name: istio-egressgateway
        enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service:
            ports:
              - port: 15020
                name: status-port
              - port: 80
                name: http2
              - port: 443
                name: https
          replicaCount: 1
      # - name: istio-ingressgateway-external
      #   enabled: true
      #   namespace: istio-system
      #   label:
      #     istio: istio-ingressgateway-external
      #   k8s:
      #     hpaSpec:
      #       minReplicas: 1
    pilot:
      enabled: true
  hub: docker.io/istio  
  profile: minimal
  tag: 1.21.0
  meshConfig:
    trustDomain: cluster.local
    # ingressService: istio-ingressgateway
    # ingressControllerMode: DEFAULT
    # ingressClass: external-istio
  values:
    defaultRevision: ""
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway: {}
    global:
      caAddress: cert-manager-istio-csr.cert-manager.svc:443
      configValidation: true
      istioNamespace: istio-system