---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  profile: default
  components:
    pilot:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      - name: istio-ingressgateway-internal
        enabled: true
        label:
          istio: istio-ingressgateway-internal
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          hpaSpec:
            minReplicas: 1
      - name: istio-ingressgateway-external
        enabled: true
        label:
          istio: istio-ingressgateway-external
        k8s:
          hpaSpec:
            minReplicas: 1
    egressGateways:
      - name: istio-egressgateway
        enabled: false