---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  profile: default
  hub: docker.io/istio
  tag: 1.21.0
  meshConfig:
    trustDomain: cluster.local
  values:
    global:
      caAddress: cert-manager-istio-csr.cert-manager.svc:443
  components:
    pilot:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      # - name: istio-ingressgateway-internal
      #   enabled: true
      #   namespace: istio-system
      #   label:
      #     istio: istio-ingressgateway-internal
      #     service.istio.io/canonical-revision: "1.21.0"
      #   k8s:
      #     serviceAnnotations:
      #       service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      #     hpaSpec:
      #       minReplicas: 1
      # - name: istio-ingressgateway-external
      #   enabled: true
      #   namespace: istio-system
      #   label:
      #     istio: istio-ingressgateway-external
      #     service.istio.io/canonical-revision: "1.21.0"
      #   k8s:
      #     hpaSpec:
      #       minReplicas: 1
    egressGateways:
      - name: istio-egressgateway
        enabled: false