---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  profile: default
  hub: "docker.io/istio"
  tag: "1.20.4"
  components:
    pilot:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
      - name: aks-istio-ingressgateway-internal
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
          serviceAnnotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service:
          - port:
              number: 80
              name: http
              protocol: HTTP
            hosts:
              - "*"
      - name: aks-istio-ingressgateway-external
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
          service:
          - port:
              number: 80
              name: http
              protocol: HTTP
            hosts:
              - "*"
    egressGateways:
      - name: istio-egressgateway
        enabled: false

