---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  profile: default
  # hub: "docker.io/istio"
  # tag: "1.20.4"
  components:
    base:
      enabled: true
    cni:
      enabled: true
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
    meshConfig:
      accessLogFile: "/dev/stdout"
      accessLogEncoding: "JSON"
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
          overlays:
            - apiVersion: v1
              kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.ports
                  value:
                    - name: status-port
                      port: 15021
                      targetPort: 15021
                      protocol: TCP
                    - name: http2
                      port: 80
                      targetPort: 8080
                      protocol: TCP
                    - name: https
                      port: 443
                      targetPort: 8443
                      protocol: TCP
      - name: istio-ingressgateway-external
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
    egressGateways:
      - name: istio-egressgateway
        enabled: false
    values:
      global:
        istiod:
          enableAnalysis: true
        proxy:
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 100Mi
      cni:
        excludeNamespaces:
          - istio-system
          - kube-system
      pilot:
        env:
          PILOT_ENABLE_STATUS: true
      sidecarInjectorWebhook:
        rewriteAppHTTPProbe: true

