---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis-cache
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: redis-cache
  install:
    remediation:
      retries: 3
  interval: 10m0s
  releaseName: redis
  values:
    # auth:
    #   existingSecret: redis-auth-secret
    # master:
    #   nodeSelector:
    #     workload_type: application_linux
    #   persistence:
    #     existingClaim: redis-cluster-pvc
    #   service:
    #     annotations:
    #       service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    #     type: LoadBalancer
    # replica:
    #   nodeSelector:
    #     workload_type: application_linux
    #   replicaCount: 1
    #   service:
    #     annotations:
    #       service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    #     type: LoadBalancer