---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis-cache
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: redis-cache
  install:
    remediation:
      retries: 3
  interval: 10m0s
  releaseName: redis
  values:
    auth:
      enabled: false
    master:
      nodeSelector:
        app: cluster
      # persistence:
      #   enabled: true
      #   size: 8Gi
      replicaCount: 3
    replica:
      nodeSelector:
        app: cluster
      # persistence:
      #   enabled: true
      #   size: 8Gi
      replicaCount: 1
