apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-cache
  namespace: redis-cache
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/redis