---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: default
spec:
  releaseName: kiali-operator
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repo: quay.io/kiali/kiali-operator
      tag: latest
    cr:
      namespace: istio-system
      create: true