# flux create hr istio-base \
#     --interval=10m \
#     --source=HelmRepository/istio \
#     --chart=istio/base 

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    defaultRevision: default
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-istio-csr
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: jetstack/cert-manager-istio-csr
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 1h0m0s
  values:
    app:
      certmanager:
        issuer:
          name: istio-ca
          kind: Issuer
          group: cert-manager.io
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: istiod
#   namespace: istio-system
# spec:
#   releaseName: istiod
#   chart:
#     spec:
#       chart: istio/istiod
#       sourceRef:
#         kind: HelmRepository
#         name: istio
#         namespace: flux-system
#   interval: 1h0m0s
#   install:
#     remediation:
#       retries: 3
#   values:
#     profile: default
#     meshConfig:
#       ingressSelector: istio-ingress
#       ingressService: istio-ingressgateway
#     pilot:
#       env:
#         K8S_INGRESS_NS: istio-ingress
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: istio-ingress
#   namespace: istio-ingress
# spec:
#   releaseName: istio-ingress
#   chart:
#     spec:
#       chart: istio/gateway
#       sourceRef:
#         kind: HelmRepository
#         name: istio
#         namespace: flux-system
#   interval: 1h0m0s
#   install:
#     remediation:
#       retries: 3
#   values:
#     gateways:
#       istio-ingressgateway:
#         serviceAnnotations:
#           service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: istio-operator
#   namespace: istio-operator
# spec:
#   releaseName: istio-operator
#   chart:
#     spec:
#       chart: manifests/charts/istio-operator
#       sourceRef:
#         kind: GitRepository
#         name: istio
#         namespace: flux-system
#   interval: 1h0m0s
#   install:
#     remediation:
#       retries: 3
#   values:
#     watchedNamespaces: istio-system
#     tolerations:
#       - effect: NoSchedule
#         key: app
#         value: "cluster"
#     affinity:
#       nodeAffinity:
#         requiredDuringSchedulingIgnoredDuringExecution:
#           nodeSelectorTerms:
#             - matchExpressions:
#                 - key: agentpool
#                   operator: In
#                   values:
#                     - poolz1
#                     - poolz2
#                     - poolz3