---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team