######################
## Airflow Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-airflow
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/airflow
  prune: true
  wait: true


######################
## Cache Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-cache
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/redis-cluster
  prune: true
  wait: true
  healthChecks:
    - kind: StatefulSet
      name: redis-master
      namespace: redis-cluster
    - kind: StatefulSet
      name: redis-replicas
      namespace: redis-cluster


######################
## Config Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-configmap
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/config-maps
  prune: true
  wait: true


######################
## Elastic Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-elastic
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/elastic
  prune: true
  wait: true
  healthChecks:
    - kind: StatefulSet
      name: elastic-system
      namespace: elastic-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-elastic-config
  namespace: flux-system
spec:
  dependsOn:
    - name: component-elastic
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/configuration/elastic
  prune: true



######################
## Cert Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-certs
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/cert-manager
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    - kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager



######################
## Mesh Component
######################
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-mesh
  namespace: flux-system
spec:
  dependsOn:
    - name: component-certs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/service-mesh
  prune: true
  wait: true
  # healthChecks:
  #   - kind: Deployment
  #     name: istio-operator
  #     namespace: istio-operator

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: software-component-mesh-certs-config
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: software-component-mesh
#     - name: software-component-mesh-certs
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./software/configuration/cert-manager
#   prune: true
#   wait: true
#   healthChecks:
#     - kind: Deployment
#       name: cert-manager-istio-csr
#       namespace: cert-manager
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: software-component-mesh-cp-config
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: software-component-mesh
#     - name: software-component-mesh-certs
#     - name: software-component-mesh-certs-config
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./software/configuration/service-mesh
#   prune: true
#   healthChecks:
#     - kind: Deployment
#       name: istiod
#       namespace: istio-system
#     - kind: Deployment
#       name: istio-ingressgateway
#       namespace: istio-system
    # - kind: Deployment
    #   name: istio-ingressgateway-external
    #   namespace: istio-system
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: software-component-mesh-monitoring
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: software-component-mesh
#     - name: software-component-mesh-certs
#     - name: software-component-mesh-certs-config
#     - name: software-component-mesh-cp-config
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./software/components/monitoring
#   prune: true
#   wait: true
#   healthChecks:
#     - kind: Deployment
#       name: prometheus-operator-grafana
#       namespace: monitoring
#     - kind: Deployment
#       name: prometheus-operator-kube-p-operator
#       namespace: monitoring
#     - kind: Deployment
#       name: prometheus-operator-kube-p-operator
#       namespace: monitoring
#     - kind: Deployment
#       name: kiali-operator
#       namespace: monitoring
